name: build-test-release

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

jobs:
  run-reusable-build-test-release:
    uses: bdebek-splunk/reusable-build-test-release/.github/workflows/main.yml@main
    secrets: inherit
