name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  run-reusable-build-test-release:
    uses: bdebek-splunk/reusable-build-test-release/.github/workflows/main.yml@main
    secrets: 
      GH_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}